// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA67VUoJKFT9pWo2taZawBiSeap2fTgEmQ',
    appId: '1:100753571599:android:86cfc918ebda052632887a',
    messagingSenderId: '100753571599',
    projectId: 'flutter-projects-9b320',
    storageBucket: 'flutter-projects-9b320.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK0_YeyUcaAoFB1G_2f3Bu5z7eUv5K7hI',
    appId: '1:100753571599:ios:ab07f1a42a81466832887a',
    messagingSenderId: '100753571599',
    projectId: 'flutter-projects-9b320',
    storageBucket: 'flutter-projects-9b320.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdTy8dI7FmDAnPMFeT2No47L1KeuRY_Bw',
    appId: '1:100753571599:web:c7edc462776a072f32887a',
    messagingSenderId: '100753571599',
    projectId: 'flutter-projects-9b320',
    authDomain: 'flutter-projects-9b320.firebaseapp.com',
    storageBucket: 'flutter-projects-9b320.firebasestorage.app',
  );
}
